<?php
/**
 * Admin dashboard: store vitals plus the pre-launch checklist.
 */
declare(strict_types=1);
require __DIR__ . '/_guard.php';

$pdo = db();

function scalar(PDO $pdo, string $sql, array $args = []): float
{
    try {
        $st = $pdo->prepare($sql);
        $st->execute($args);
        return (float)$st->fetchColumn();
    } catch (Throwable $e) {
        return 0.0;
    }
}

$counts = [
    'orders'   => (int)scalar($pdo, 'SELECT COUNT(*) FROM orders'),
    'products' => (int)scalar($pdo, 'SELECT COUNT(*) FROM products'),
    'users'    => (int)scalar($pdo, 'SELECT COUNT(*) FROM users'),
    'unread'   => (int)scalar($pdo, 'SELECT COUNT(*) FROM contact_messages WHERE is_read = 0'),
    'reviews'  => (int)scalar($pdo, 'SELECT COUNT(*) FROM reviews'),
];
$revenueAll  = scalar($pdo, "SELECT COALESCE(SUM(total),0) FROM orders WHERE status NOT IN ('cancelled','refunded')");
$revenue7d   = scalar($pdo, "SELECT COALESCE(SUM(total),0) FROM orders
                             WHERE status NOT IN ('cancelled','refunded') AND created_at >= NOW() - INTERVAL 7 DAY");
$openOrders  = (int)scalar($pdo, "SELECT COUNT(*) FROM orders WHERE status IN ('pending','paid','processing')");

try {
    $recent = $pdo->query(
        'SELECT id, full_name, email, total, status, created_at FROM orders ORDER BY id DESC LIMIT 8'
    )->fetchAll();
} catch (Throwable $e) {
    $recent = [];
}

/* ---- Pre-launch checklist ------------------------------------------------ */
$stale  = placeholder_settings();
$checks = [];

$checks[] = [
    'ok'    => empty($stale),
    'label' => 'Real business contact details',
    'detail' => $stale
        ? count($stale) . ' field(s) still hold shipped placeholder values: '
          . implode(', ', array_map(static fn($s) => $s['label'], $stale))
        : 'Address, phone and email have all been replaced with real values.',
    'link'  => admin_url('settings.php#grp-contact'),
    'cta'   => 'Edit contact settings',
];

$socialCount = count(setting_social_links());
$checks[] = [
    'ok'     => true,
    'soft'   => $socialCount === 0,
    'label'  => 'Social profiles',
    'detail' => $socialCount > 0
        ? $socialCount . ' profile link(s) configured.'
        : 'None set. That is fine — an empty list is honest. Only add links to profiles that actually exist.',
    'link'   => admin_url('settings.php#grp-social'),
    'cta'    => 'Add profiles',
];

$pageCount = count(all_pages(true));
$checks[] = [
    'ok'     => $pageCount >= 7,
    'label'  => 'Policy pages published',
    'detail' => $pageCount . ' page(s) published. Shipping, returns, refunds, privacy and terms should all be live '
              . 'and should describe what you actually do.',
    'link'   => admin_url('pages.php'),
    'cta'    => 'Review pages',
];

$fakeCompare = (int)scalar($pdo, 'SELECT COUNT(*) FROM products WHERE compare_at_price IS NOT NULL AND compare_at_price <= base_price');
$checks[] = [
    'ok'     => $fakeCompare === 0,
    'label'  => 'No invented reference prices',
    'detail' => $fakeCompare === 0
        ? 'Strikethrough "was" prices only appear where a genuine compare-at price is stored.'
        : $fakeCompare . ' product(s) have a compare-at price at or below the selling price.',
    'link'   => null,
];

$checks[] = [
    'ok'     => $counts['reviews'] === 0,
    'label'  => 'No machine-generated reviews',
    'detail' => $counts['reviews'] === 0
        ? 'No reviews stored. Star ratings and AggregateRating markup stay hidden until real customers write them.'
        : $counts['reviews'] . ' review(s) stored. If any were generated by setup.php --demo-reviews, delete them: '
          . 'presenting synthetic text as customer reviews breaches the FTC\'s 2024 rule and carries civil penalties.',
    'link'   => admin_url('reviews.php'),
    'cta'    => 'Manage reviews',
];

$indexOn = setting_bool('robots_index');
$blockers = count(array_filter($checks, static fn($c) => empty($c['ok'])));
$checks[] = [
    'ok'     => $indexOn && $blockers === 0,
    'soft'   => !$indexOn,
    'label'  => 'Search engine indexing',
    'detail' => $indexOn
        ? ($blockers === 0
            ? 'Indexing is on and every check above passes.'
            : 'Indexing is ON while ' . $blockers . ' check(s) still fail. Google may crawl placeholder details.')
        : 'Indexing is off (noindex). Turn it on once the checks above pass.',
    'link'   => admin_url('settings.php#grp-seo'),
    'cta'    => 'SEO settings',
];

$adminTitle = 'Dashboard';
require __DIR__ . '/_layout.php';
?>

<div class="row g-3 mb-4">
  <div class="col-6 col-lg-3"><div class="stat"><div class="k">Revenue (all time)</div><div class="v"><?= h(money($revenueAll)) ?></div></div></div>
  <div class="col-6 col-lg-3"><div class="stat"><div class="k">Revenue (7 days)</div><div class="v"><?= h(money($revenue7d)) ?></div></div></div>
  <div class="col-6 col-lg-3"><div class="stat"><div class="k">Open orders</div><div class="v"><?= $openOrders ?></div></div></div>
  <div class="col-6 col-lg-3"><div class="stat"><div class="k">Unread messages</div><div class="v"><?= $counts['unread'] ?></div></div></div>
</div>

<div class="row g-4">
  <div class="col-lg-7">
    <section class="card-a">
      <div class="hd">
        Pre-launch checklist
        <?php if ($blockers > 0): ?>
          <span class="badge text-bg-warning ms-auto"><?= $blockers ?> to fix</span>
        <?php else: ?>
          <span class="badge text-bg-success ms-auto">All clear</span>
        <?php endif; ?>
      </div>
      <div class="bd">
        <p class="text-muted small">
          These are the things that make a store look real to a customer — and to Google.
          Work through them before you take live orders.
        </p>
        <?php foreach ($checks as $c): ?>
          <?php
            $state = !empty($c['ok']) ? 'ok' : (!empty($c['soft']) ? 'soft' : 'bad');
            $icon  = $state === 'ok' ? '✓' : ($state === 'soft' ? '•' : '!');
            $color = $state === 'ok' ? '#1a7f37' : ($state === 'soft' ? '#6b7280' : '#c8102e');
          ?>
          <div class="d-flex gap-3 py-3" style="border-top:1px solid var(--line)">
            <div style="color:<?= $color ?>;font-weight:700;font-size:1.05rem;width:16px"><?= $icon ?></div>
            <div class="flex-grow-1">
              <div style="font-weight:600;font-size:.92rem;color:<?= $state === 'bad' ? '#c8102e' : 'inherit' ?>">
                <?= h($c['label']) ?>
              </div>
              <div class="small text-muted"><?= h($c['detail']) ?></div>
              <?php if (!empty($c['link']) && $state !== 'ok'): ?>
                <a class="small" href="<?= h($c['link']) ?>"><?= h($c['cta'] ?? 'Fix this') ?> →</a>
              <?php endif; ?>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    </section>
  </div>

  <div class="col-lg-5">
    <section class="card-a mb-4">
      <div class="hd">Recent orders <a class="ms-auto small fw-normal" href="<?= admin_url('orders.php') ?>">View all</a></div>
      <div class="bd p-0">
        <?php if (!$recent): ?>
          <p class="text-muted small p-3 mb-0">No orders yet.</p>
        <?php else: ?>
          <table class="table table-sm">
            <thead><tr><th class="ps-3">#</th><th>Customer</th><th>Status</th><th class="text-end pe-3">Total</th></tr></thead>
            <tbody>
              <?php foreach ($recent as $o): ?>
                <tr>
                  <td class="ps-3"><a href="<?= admin_url('order.php?id=' . (int)$o['id']) ?>"><?= (int)$o['id'] ?></a></td>
                  <td><?= h(mb_strimwidth((string)$o['full_name'], 0, 22, '…')) ?></td>
                  <td><span class="badge text-bg-<?= h(order_status_class((string)$o['status'])) ?>"><?= h(order_status_label((string)$o['status'])) ?></span></td>
                  <td class="text-end pe-3"><?= h(money($o['total'])) ?></td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
        <?php endif; ?>
      </div>
    </section>

    <section class="card-a">
      <div class="hd">Catalog</div>
      <div class="bd">
        <div class="d-flex justify-content-between small py-1"><span class="text-muted">Products</span><strong><?= number_format($counts['products']) ?></strong></div>
        <div class="d-flex justify-content-between small py-1"><span class="text-muted">Registered customers</span><strong><?= number_format($counts['users']) ?></strong></div>
        <div class="d-flex justify-content-between small py-1"><span class="text-muted">Orders</span><strong><?= number_format($counts['orders']) ?></strong></div>
        <div class="d-flex justify-content-between small py-1"><span class="text-muted">Reviews</span><strong><?= number_format($counts['reviews']) ?></strong></div>
      </div>
    </section>
  </div>
</div>

<?php require __DIR__ . '/_layout_end.php'; ?>
