<?php
/**
 * Review moderation — and, importantly, the tool for purging the synthetic
 * reviews that setup.php --demo-reviews can generate.
 *
 * Presenting machine-generated text as genuine customer reviews breaches the
 * FTC's 2024 rule on fake reviews and carries civil penalties, and marking it
 * up as schema.org AggregateRating is a separate structured-data violation.
 * product.php only emits aggregateRating when real reviews exist.
 */
declare(strict_types=1);
require __DIR__ . '/_guard.php';

$pdo = db();

if ($_SERVER['REQUEST_METHOD'] === 'POST' && csrf_check()) {
    $action = (string)($_POST['action'] ?? '');

    if ($action === 'delete') {
        $rid = (int)($_POST['id'] ?? 0);
        if ($rid > 0) {
            $pdo->prepare('DELETE FROM reviews WHERE id = ?')->execute([$rid]);
            flash('Review deleted.');
        }
    } elseif ($action === 'purge_all' && (string)($_POST['confirm'] ?? '') === 'DELETE') {
        // Scoped by a literal WHERE on the table's own key range rather than an
        // unqualified DELETE, and gated behind typing DELETE — this wipes every
        // review and there is no undo.
        $n = (int)$pdo->query('SELECT COUNT(*) FROM reviews')->fetchColumn();
        $pdo->exec('DELETE FROM reviews WHERE id > 0');
        flash("Deleted {$n} review(s).");
    }
    header('Location: ' . admin_url('reviews.php'));
    exit;
}

$total = (int)$pdo->query('SELECT COUNT(*) FROM reviews')->fetchColumn();
$page  = max(1, (int)($_GET['page'] ?? 1));
$per   = 40;
$offset = ($page - 1) * $per;
$pages = max(1, (int)ceil($total / $per));

$rows = $pdo->query(
    "SELECT r.id, r.author, r.rating, r.body, r.created_at, p.name AS product_name, p.handle
     FROM reviews r LEFT JOIN products p ON p.id = r.product_id
     ORDER BY r.id DESC LIMIT {$per} OFFSET {$offset}"
)->fetchAll();

$adminTitle = 'Reviews';
require __DIR__ . '/_layout.php';
?>

<?php if ($total > 0): ?>
  <div class="alert alert-warning small">
    <strong><?= number_format($total) ?> review(s) stored.</strong>
    If any of these were generated by <code class="ph">setup.php --demo-reviews</code>, delete them before
    the store goes live. Synthetic text presented as customer reviews is prohibited by the FTC's 2024 rule
    and carries civil penalties. Star ratings and <code class="ph">AggregateRating</code> markup are
    suppressed sitewide while no reviews exist.
  </div>

  <details class="card-a mb-3">
    <summary class="hd" style="cursor:pointer">Delete every review</summary>
    <div class="bd">
      <p class="small text-muted">
        Removes all <?= number_format($total) ?> reviews. There is no undo.
      </p>
      <form method="post" class="d-flex gap-2 align-items-center flex-wrap">
        <input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>">
        <input type="hidden" name="action" value="purge_all">
        <input class="form-control" name="confirm" placeholder="Type DELETE to confirm" style="max-width:230px" required>
        <button class="btn btn-danger">Delete all reviews</button>
      </form>
    </div>
  </details>
<?php endif; ?>

<section class="card-a">
  <div class="bd p-0">
    <?php if (!$rows): ?>
      <p class="text-muted small p-3 mb-0">
        No reviews stored. Star ratings stay hidden until real customers write them — which is the honest default.
      </p>
    <?php else: ?>
      <div class="table-responsive">
        <table class="table">
          <thead><tr><th class="ps-3">Product</th><th>Author</th><th>Rating</th><th>Review</th><th class="text-end pe-3"></th></tr></thead>
          <tbody>
            <?php foreach ($rows as $r): ?>
              <tr>
                <td class="ps-3 small">
                  <?php if (!empty($r['handle'])): ?>
                    <a target="_blank" href="<?= url('product.php?handle=' . urlencode((string)$r['handle'])) ?>">
                      <?= h(mb_strimwidth((string)$r['product_name'], 0, 34, '…')) ?>
                    </a>
                  <?php else: ?>
                    <span class="text-muted">(deleted product)</span>
                  <?php endif; ?>
                </td>
                <td class="small"><?= h((string)$r['author']) ?></td>
                <td class="small" style="color:#f5a623;white-space:nowrap"><?= str_repeat('★', max(0, min(5, (int)$r['rating']))) ?></td>
                <td class="small text-muted"><?= h(mb_strimwidth((string)$r['body'], 0, 90, '…')) ?></td>
                <td class="text-end pe-3">
                  <form method="post" class="d-inline" onsubmit="return confirm('Delete this review?')">
                    <input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>">
                    <input type="hidden" name="action" value="delete">
                    <input type="hidden" name="id" value="<?= (int)$r['id'] ?>">
                    <button class="btn btn-sm btn-outline-danger" style="font-size:.72rem">Delete</button>
                  </form>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    <?php endif; ?>
  </div>
</section>

<?php if ($pages > 1): ?>
  <nav class="mt-3">
    <ul class="pagination pagination-sm">
      <?php for ($i = 1; $i <= $pages; $i++): ?>
        <li class="page-item<?= $i === $page ? ' active' : '' ?>">
          <a class="page-link" href="<?= admin_url('reviews.php?page=' . $i) ?>"><?= $i ?></a>
        </li>
      <?php endfor; ?>
    </ul>
  </nav>
<?php endif; ?>

<?php require __DIR__ . '/_layout_end.php'; ?>
