<?php
declare(strict_types=1);

/**
 * Pre-launch data cleanup for the Aurel Time storefront.
 *
 * Clears the data that would get the store rejected by Google Merchant Center
 * or breach UK consumer law, and fills in the business facts the policy pages
 * render from:
 *   - reviews        all rows deleted. Every one was generated by the demo
 *                    seeder; fake reviews are banned (DMCC Act 2024) and they
 *                    fed aggregateRating structured data.
 *   - variants       one per product. The Core/Signature/Elite tiers were the
 *                    old replica grades renamed: same watch, same photo, three
 *                    prices. The Signature price is kept (median variant when a
 *                    product has no Signature row) and relabelled "Standard".
 *   - products       base_price follows the kept variant; "AUREL TIME" in names
 *                    and descriptions becomes "Aurel Time" (no all-caps titles
 *                    in the feed); the spec sentence is made grammatical.
 *   - orders 3, 4    the owner's own test orders, carrying the old counterfeit
 *                    line items. Removed with their order_items.
 *   - settings       emails on aureltime.site, support hours, carriers,
 *                    destinations, social share image.
 *
 * Idempotent: a second run plans zero changes.
 *
 * Usage:
 *   php scripts/launch-cleanup.php            # dry run, prints the plan, writes nothing
 *   php scripts/launch-cleanup.php --commit   # applies it
 */

require_once __DIR__ . '/../app/helpers.php';

const KEEP_GRADE  = 'Signature';
const NEW_GRADE   = 'Standard';
const TEST_ORDERS = [3, 4];

const SETTINGS = [
    'contact_email'       => 'contact@aureltime.site',
    'support_email'       => 'support@aureltime.site',
    'orders_email'        => 'orders@aureltime.site',
    'support_hours'       => 'Mon–Sat, 9:00–18:00 (UK time)',
    'ship_carriers'       => 'Royal Mail Special Delivery, DPD, DHL Express',
    'ship_countries_note' => 'We ship across the United Kingdom with Royal Mail Special Delivery and DPD, '
                           . 'and internationally with DHL Express. Import duties and taxes on international '
                           . 'orders are the responsibility of the recipient.',
    'og_image'            => 'https://aureltime.site/assets/brand/aurel-time-og.png',
];

/** Bare material labels from the old name parser -> a phrase that reads after "It has". */
const SPEC_PHRASES = [
    'leather strap'    => 'a leather strap',
    'rubber strap'     => 'a rubber strap',
    'stainless steel'  => 'stainless steel construction',
    'titanium'         => 'titanium construction',
    'ceramic'          => 'ceramic construction',
    'carbon composite' => 'carbon composite construction',
    'rose gold tone'   => 'a rose gold-tone finish',
    'gold tone'        => 'a gold-tone finish',
    'platinum tone'    => 'a platinum-tone finish',
    'two-tone'         => 'a two-tone finish',
];

$COMMIT = in_array('--commit', $argv, true);

function fix_spec_sentence(string $desc): string {
    return preg_replace_callback('/It has ([^.]+)\./', function (array $m): string {
        $items = preg_split('/, | and /', $m[1]);
        foreach ($items as &$it) {
            $it = SPEC_PHRASES[$it] ?? $it;
            $it = preg_replace('/^a (?=[aeiou])/', 'an ', $it);
        }
        unset($it);
        $last = array_pop($items);
        return 'It has ' . ($items ? implode(', ', $items) . ' and ' : '') . $last . '.';
    }, $desc, 1);
}

function fix_text(string $s): string {
    return str_replace('AUREL TIME', 'Aurel Time', $s);
}

$pdo = db();
printf("=== LAUNCH CLEANUP (%s) ===\n\n", $COMMIT ? 'COMMIT' : 'DRY RUN');

// ---------------------------------------------------------------- plan
$reviewCount = (int)$pdo->query('SELECT COUNT(*) FROM reviews')->fetchColumn();
printf("Reviews to delete: %d\n", $reviewCount);

$variants = $pdo->query('SELECT id, product_id, grade, price FROM variants ORDER BY product_id, price, id')
                ->fetchAll(PDO::FETCH_ASSOC);
$byProduct = [];
foreach ($variants as $v) $byProduct[(int)$v['product_id']][] = $v;

$keep = [];      // product_id => kept variant row
$drop = [];      // variant ids to delete
$fallback = 0;
foreach ($byProduct as $pid => $vs) {
    $k = null;
    foreach ($vs as $v) if ($v['grade'] === KEEP_GRADE) { $k = $v; break; }
    if ($k === null) {
        $k = $vs[intdiv(count($vs) - 1, 2)];   // median by price
        if (count($vs) > 1 || $k['grade'] !== NEW_GRADE) $fallback++;
    }
    $keep[$pid] = $k;
    foreach ($vs as $v) if ($v['id'] !== $k['id']) $drop[] = (int)$v['id'];
}
$regrade = count(array_filter($keep, fn($v) => $v['grade'] !== NEW_GRADE));
printf("Variants: %d products, %d variants deleted, %d relabelled '%s' (%d via median fallback)\n",
    count($keep), count($drop), $regrade, NEW_GRADE, $fallback);

$products = $pdo->query('SELECT id, name, description, base_price FROM products ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);
$prodPlan = [];
foreach ($products as $p) {
    $id    = (int)$p['id'];
    $name  = fix_text((string)$p['name']);
    $desc  = $p['description'] === null ? null : fix_spec_sentence(fix_text((string)$p['description']));
    $price = isset($keep[$id]) ? (string)$keep[$id]['price'] : (string)$p['base_price'];
    if ($name !== $p['name'] || $desc !== $p['description'] || (float)$price !== (float)$p['base_price']) {
        $prodPlan[$id] = ['name' => $name, 'description' => $desc, 'base_price' => $price];
    }
}
printf("Products to update: %d\n", count($prodPlan));
foreach ([1, 4, 500] as $id) {
    if (!isset($prodPlan[$id])) continue;
    preg_match('/It has [^.]+\./', (string)$prodPlan[$id]['description'], $m);
    printf("  #%d £%s  %s\n       %s\n", $id, $prodPlan[$id]['base_price'], $prodPlan[$id]['name'], $m[0] ?? '');
}

$in = implode(',', TEST_ORDERS);
$orderCount = (int)$pdo->query("SELECT COUNT(*) FROM orders WHERE id IN ($in)")->fetchColumn();
printf("Test orders to delete: %d\n", $orderCount);

$setPlan = [];
foreach (SETTINGS as $k => $v) {
    $cur = $pdo->query('SELECT svalue FROM settings WHERE skey = ' . $pdo->quote($k))->fetchColumn();
    if ($cur !== $v) $setPlan[$k] = $v;
}
echo "Settings to set:\n";
foreach ($setPlan as $k => $v) printf("  %-20s -> %s\n", $k, $v);

if (!$COMMIT) {
    echo "\nDry run complete. Nothing written. Re-run with --commit to apply.\n";
    exit(0);
}

// ---------------------------------------------------------------- write
$pdo->beginTransaction();
try {
    $pdo->exec('DELETE FROM reviews');

    foreach (array_chunk($drop, 500) as $chunk) {
        $pdo->exec('DELETE FROM variants WHERE id IN (' . implode(',', $chunk) . ')');
    }
    $pdo->prepare('UPDATE variants SET grade = ? WHERE grade <> ?')->execute([NEW_GRADE, NEW_GRADE]);

    $up = $pdo->prepare('UPDATE products SET name = ?, description = ?, base_price = ? WHERE id = ?');
    foreach ($prodPlan as $id => $p) $up->execute([$p['name'], $p['description'], $p['base_price'], $id]);

    $pdo->exec("DELETE FROM order_items WHERE order_id IN ($in)");
    $pdo->exec("DELETE FROM orders WHERE id IN ($in)");

    $us = $pdo->prepare(
        'INSERT INTO settings (skey, svalue) VALUES (?, ?) ON DUPLICATE KEY UPDATE svalue = VALUES(svalue)'
    );
    foreach ($setPlan as $k => $v) $us->execute([$k, $v]);

    $pdo->commit();
    printf("\nCommitted: %d reviews, %d variants, %d products, %d orders, %d settings.\n",
        $reviewCount, count($drop), count($prodPlan), $orderCount, count($setPlan));
} catch (Throwable $e) {
    $pdo->rollBack();
    echo "\nROLLED BACK: " . $e->getMessage() . "\n";
    exit(1);
}
