<?php
declare(strict_types=1);

/**
 * Regenerates the production catalogue dump from the current local database.
 *
 * Replaces the hand-made seed-products.sql, which was cut before the catalogue
 * was de-branded and therefore still carries the maison names. Written as a
 * generator rather than a one-off because the catalogue has to be re-cut again
 * once the supplier-CDN imagery is replaced.
 *
 * Output matches the original file's shape exactly, because those choices were
 * load-bearing on this host:
 *   - INSERT statements capped at 32 KB. Straight mysqldump emitted the
 *     product_images rows as one 795 KB statement, which dies with "MySQL
 *     server has gone away" against the common 1 MB max_allowed_packet.
 *   - FOREIGN_KEY_CHECKS off around the load, TRUNCATE children before parents.
 *   - Explicit column lists, so a later column addition cannot silently
 *     shift values into the wrong field.
 *   - Rows keep their original primary keys, so product_images.product_id and
 *     variants.product_id still point at the right products.
 *
 * It refuses to write a file containing a third-party trademark. That check is
 * the whole point: this is the artefact that reaches the public server.
 *
 * Usage:  php scripts/make-catalog-dump.php
 */

require_once __DIR__ . '/../app/helpers.php';

const MAX_STATEMENT = 32768;

/** Load order (parents first). Truncation runs in reverse of the FK direction. */
const LOAD_ORDER     = ['brands', 'products', 'product_images', 'variants'];
const TRUNCATE_ORDER = ['product_images', 'variants', 'products', 'brands'];

const TM_TERMS = [
    'Rolex', 'Omega', 'Cartier', 'Breitling', 'Hublot', 'Audemars', 'Piguet',
    'Patek', 'Philippe', 'Panerai', 'Richard Mille', 'Tudor', 'Submariner',
    'Sea-Dweller', 'Deepsea', 'Yacht-Master', 'Daytona', 'Speedmaster',
    'Navitimer', 'Chronomat', 'GMT-Master', 'Datejust', 'Day-Date', 'Cellini',
    'Calatrava', 'Santos', 'De Ville', 'Royal Oak', 'Nautilus', 'Aquanaut',
    'Big Bang', 'Classic Fusion', 'Luminor', 'Radiomir', 'Milgauss', 'Air-King',
    'Oyster', 'Constellation', 'Ballon Bleu', 'Superocean', 'Replica', 'Clone',
];

$pdo  = db();
$root = dirname(__DIR__);

/** Quote one value for SQL, preserving NULL and numeric literals. */
function sql_value(PDO $pdo, $v, string $type): string {
    if ($v === null) return 'NULL';
    if (preg_match('/^(int|decimal|float|double|bigint|smallint|tinyint)/i', $type)) {
        return (string)$v;
    }
    return $pdo->quote((string)$v);
}

$counts = [];
$sql    = [];

foreach (TRUNCATE_ORDER as $t) $sql[] = "TRUNCATE TABLE `$t`;";
$truncates = implode("\n", $sql);

$body = [];
foreach (LOAD_ORDER as $table) {
    $cols  = $pdo->query("SHOW COLUMNS FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
    $names = array_column($cols, 'Field');
    $types = array_combine($names, array_column($cols, 'Type'));
    $colList = '`' . implode('`, `', $names) . '`';
    $prefix  = "INSERT INTO `$table` ($colList) VALUES ";

    $rows = $pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
    $counts[$table] = count($rows);

    $tuples = [];
    foreach ($rows as $r) {
        $vals = [];
        foreach ($names as $n) $vals[] = sql_value($pdo, $r[$n], $types[$n]);
        $tuples[] = '(' . implode(',', $vals) . ')';
    }

    // Pack tuples into statements that stay under MAX_STATEMENT.
    $buf = '';
    foreach ($tuples as $tup) {
        $candidate = $buf === '' ? $tup : $buf . ',' . $tup;
        if (strlen($prefix) + strlen($candidate) + 1 > MAX_STATEMENT && $buf !== '') {
            $body[] = $prefix . $buf . ';';
            $buf = $tup;
        } else {
            $buf = $candidate;
        }
    }
    if ($buf !== '') $body[] = $prefix . $buf . ';';
}

$brandNames = $pdo->query('SELECT name FROM brands ORDER BY name')->fetchAll(PDO::FETCH_COLUMN);
$brandCsv   = implode(', ', $brandNames);

$header = <<<HDR
-- =====================================================================
--  AUREL TIME — CATALOG SEED (products only)
-- =====================================================================
--  Loads the product catalog into a database whose tables ALREADY EXIST.
--  Run seed.sql first if the database is empty; this file creates nothing.
--
--    cPanel → phpMyAdmin → select `dieuaxvb_watches` → Import
--    or:  mysql -u dieuaxvb_watches -p dieuaxvb_watches < seed-products.sql
--
--  Generated by scripts/make-catalog-dump.php from the de-branded catalogue.
--  Do not hand-edit: regenerate instead.
--
--  WHAT IT REPLACES
--    brands         {$counts['brands']}      wiped and reloaded
--    products       {$counts['products']}   wiped and reloaded
--    product_images {$counts['product_images']}   wiped and reloaded
--    variants       {$counts['variants']}   wiped and reloaded
--
--  Collections: {$brandCsv}
--
--  WHAT IT LEAVES ALONE
--    settings, content_pages, users, orders, order_items, contact_messages
--    Store configuration, policy pages, your admin login and any real orders
--    all survive. That is the point of this file over seed.sql.
--
--    order_items has NO foreign key onto products — it stores the product name
--    and grade denormalised — so replacing the catalog cannot alter or orphan
--    what a past customer actually bought.
--
--  THIS FILE DOES NOT UPDATE SETTINGS OR PAGES. Import deploy/rebrand-settings.sql
--  alongside this file: it carries the Aurel Time identity settings, the UK policy
--  pages and the review purge. Without it the storefront serves the new catalog
--  under the old store name.
--
--  RE-RUNNABLE. The four catalog tables are truncated first, so importing
--  twice gives the same {$counts['products']} products rather than double.
--  Rows carry their original primary keys.
--
--  NOTE: products.image still points at the supplier CDN. Those photographs
--  show third-party trademarked dials. De-branding the text did not change
--  the pictures — do not submit this catalog to any ad channel until the
--  imagery is replaced and this file is regenerated.
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

HDR;

$out = $header . "\n" . $truncates . "\n\n" . implode("\n", $body) . "\n\nSET FOREIGN_KEY_CHECKS = 1;\n";

// ---- refuse to emit a file carrying a trademark -----------------------
$found = [];
foreach (TM_TERMS as $t) {
    if (stripos($out, $t) !== false) $found[] = $t;
}
// The header intentionally names the risk in prose; ignore matches there.
$bodyOnly = substr($out, strpos($out, 'SET NAMES'));
$found = array_values(array_filter($found, fn($t) => stripos($bodyOnly, $t) !== false));

if ($found) {
    echo "ABORT — dump still contains trademarks: " . implode(', ', $found) . "\n";
    exit(1);
}

file_put_contents("$root/seed-products.sql", $out);
printf("wrote seed-products.sql  (%s KB, %d statements, longest %d bytes)\n",
    number_format(strlen($out) / 1024, 1), count($body), max(array_map('strlen', $body)));
foreach ($counts as $t => $n) printf("  %-16s %5d rows\n", $t, $n);

// ---- settings patch ---------------------------------------------------
$keys = [
    'site_name', 'logo_text_a', 'logo_text_b', 'tagline', 'meta_description',
    'contact_email', 'support_email', 'orders_email', 'support_hours',
    'ship_carriers', 'ship_countries_note', 'og_image',
];
$lines = [];
foreach ($keys as $k) {
    $v = $pdo->query('SELECT svalue FROM settings WHERE skey = ' . $pdo->quote($k))->fetchColumn();
    if ($v === false) continue;
    // Upsert: some of these keys may never have been written on the live server.
    $lines[] = 'INSERT INTO `settings` (`skey`, `svalue`) VALUES (' . $pdo->quote($k) . ', '
             . $pdo->quote((string)$v) . ') ON DUPLICATE KEY UPDATE `svalue` = VALUES(`svalue`);';
}

// Policy pages, so production gets the UK wording rather than the old US text.
$pageLines = [];
foreach ($pdo->query('SELECT slug, title, body, meta_desc FROM content_pages ORDER BY sort_order') as $pg) {
    $pageLines[] = 'UPDATE `content_pages` SET `title` = ' . $pdo->quote((string)$pg['title'])
                 . ', `body` = ' . $pdo->quote((string)$pg['body'])
                 . ', `meta_desc` = ' . $pdo->quote((string)$pg['meta_desc'])
                 . ' WHERE `slug` = ' . $pdo->quote((string)$pg['slug']) . ';';
}

$patch = "-- AUREL TIME rebrand — storefront identity, policy pages and launch cleanup.\n"
       . "-- Companion to seed-products.sql, which deliberately leaves these tables alone.\n"
       . "-- Safe to re-run. Does NOT touch robots_index; indexing stays off until launch.\n\n"
       . "SET NAMES utf8mb4;\n\n"
       . "-- Every review was machine-generated by the old demo seeder (banned under the\n"
       . "-- DMCC Act 2024, and it fed star ratings to Google). Real reviews only from here.\n"
       . "DELETE FROM `reviews`;\n\n"
       . implode("\n", $lines) . "\n\n"
       . implode("\n", $pageLines) . "\n";

@mkdir("$root/deploy", 0775, true);
file_put_contents("$root/deploy/rebrand-settings.sql", $patch);
printf("wrote deploy/rebrand-settings.sql  (%d settings, %d pages, reviews purge)\n", count($lines), count($pageLines));
